# Generated by Django 4.0 on 2021-12-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JannetLee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=8, upload_to='uploads/articles/'),
            preserve_default=False,
        ),
    ]
