# Generated by Django 4.0 on 2021-12-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JannetLee', '0005_post_attack_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=20, verbose_name='email')),
                ('message', models.TextField(max_length=125, verbose_name='message')),
                ('mobile', models.CharField(max_length=20, verbose_name='phone')),
            ],
        ),
    ]
