# Generated by Django 4.0 on 2021-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JannetLee', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='Type_of_Enquiry',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Type_of_Enquiry'),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=20, verbose_name='email')),
                ('message', models.TextField(max_length=125, verbose_name='message')),
                ('mobile', models.CharField(max_length=20, verbose_name='phone')),
                ('Type_of_Enquiry', models.TextField(blank=True, max_length=25, null=True, verbose_name='Type_of_Enquiry')),
                ('attendees', models.ManyToManyField(blank=True, to='JannetLee.MyUser')),
            ],
        ),
    ]
