# Generated by Django 4.0 on 2021-12-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JannetLee', '0007_myuser_contact_type_of_enquiry_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Type_of_Enquiry',
            field=models.TextField(blank=True, max_length=55, null=True, verbose_name='Type_of_Enquiry'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=255, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Type_of_Enquiry',
            field=models.TextField(blank=True, max_length=55, null=True, verbose_name='Type_of_Enquiry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, to='JannetLee.MyUser'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(max_length=255, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
