# Generated by Django 4.0 on 2021-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JannetLee', '0008_myuser_mobile_alter_contact_type_of_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
