# Generated by Django 4.0 on 2021-12-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JannetLee', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='JannetLee.category'),
        ),
    ]
